server:
  port: 8080

spring:
  application:
    name: candidate-system

  # ===============================
  # DATASOURCE (MySQL)
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/candidate_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  # ===============================
  # FLYWAY
  # ===============================
  flyway:
    enabled: false #true
    locations: classpath:/db/migration

  # ===============================
  # SPRING SECURITY
  # ===============================
  security:
    user:
      # Solo para ambientes de desarrollo
      name: admin
      password: admin123
      roles: ADMIN

# ===============================
# JWT CONFIGURATION
# ===============================
jwt:
  secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  expiration-ms: 3600000 # 1 hora

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# ===============================
# ACTUATOR / MONITORING
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: candidate-system

# ===============================
# LOGGING
# ===============================
logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# ===============================
# APP CUSTOM PROPERTIES
# ===============================
app:
  life-expectancy-years: 75
